### ISSUE TITLE
you are using an outdated version of the cmd5 command definition

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/extstreet#1]
we updated cmd5 a long time ago and you are still using an outdated version in your code, that i created when i set up the reporsitory.

While looking at the project I thought you should probably make sure you update cmd5 and develop appropriate commands

**Comment by suunni-zz** [comment]
Cloned the cloudmesh.common, cloudmesh.cmd5, cloudmesh.bar. Getting import error
```

(ENV2) sunanda@sunanda-VirtualBox:~/github/cloudmesh/cloudmesh.bar$ cms
Traceback (most recent call last):
  File "/home/sunanda/ENV2/bin/cms", line 11, in <module>
    load_entry_point('cloudmesh.cmd5==1.2.6', 'console_scripts', 'cms')()
  File "/home/sunanda/ENV2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/sunanda/ENV2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/home/sunanda/ENV2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/home/sunanda/ENV2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/sunanda/ENV2/lib/python2.7/site-packages/cloudmesh_cmd5-0.0.1-py2.7.egg/cloudmesh/shell/shell.py", line 12, in <module>
    from cloudmesh.common.util import get_python
ImportError: cannot import name get_python

```

**Comment by laszewsk** [comment]
Your output shows cloudmesh_cmd5-0.0.1
New versions of cloudmesh have been released for cloudmesh cmd5, common a long time ago. Easiest may be to if you install all of them in anew virtualenv, you can even use the command

cms sys command generate YOURNEWCOMMANDNAME

to create a new command.

**Comment by laszewsk** [comment]
I fixed your code to jumpstart your efforts

$ sign hallo Gregor
{'hallo': True, 'IMAGE': None, 'detect': False, 'NAME': 'Gregor'}
Hello Sign Gregor

$ cms sign detect Gregor
{'hallo': False, 'IMAGE': 'Gregor', 'detect': True, 'NAME': None}

**Comment by suunni-zz** [comment]
I created a new env ENV1 and recompiled and installed. I am getting error
``

(ENV1) sunanda@sunanda-VirtualBox:~/github/cloudmesh/cloudmesh.bar$ cms var timer=on
Traceback (most recent call last):
  File "/home/sunanda/ENV1/bin/cms", line 11, in <module>
    load_entry_point('cloudmesh.cmd5==1.2.6', 'console_scripts', 'cms')()
  File "/home/sunanda/ENV1/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/sunanda/ENV1/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/home/sunanda/ENV1/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/home/sunanda/ENV1/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/sunanda/ENV1/lib/python2.7/site-packages/cloudmesh.cmd5-1.2.6-py2.7.egg/cloudmesh/shell/shell.py", line 135, in <module>
    class CMShell(Cmd, PluginCommandClasses):
  File "/home/sunanda/ENV1/lib/python2.7/site-packages/cloudmesh.cmd5-1.2.6-py2.7.egg/cloudmesh/shell/shell.py", line 153, in CMShell
    variable = shelve.open(filename)
  File "/usr/local/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/local/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/usr/local/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
gdbm.error: (2, 'No such file or directory')
``

**Comment by laszewsk** [comment]
i can not replicate this. Have you installed the code from source e..g did a clone on cmd5 and comon and said make source in cmd5?
also you need to say cms once so the dbs are created just in case

**Comment by laszewsk** [comment]
also not eyou do not need bar as everything is already set up i extstreet

**Comment by suunni-zz** [comment]
Yes, in the fresh environment i ran "python setup.py install ; pip install ." in cloudmesh.common, cloudmesh.cmd5, cloudmesh.bar. 
Just running "cms" also causes the same error.

**Comment by suunni-zz** [comment]
should i run make first

**Comment by laszewsk** [comment]
get online into zoom

**Comment by laszewsk** [comment]
I am in zoom now

**Comment by suunni-zz** [comment]
ok professor
